version: "3"
services:
    web:
        environment:
            VIRTUAL_HOST: wahlomat.mariozechner.at
            LETSENCRYPT_HOST: wahlomat.mariozechner.at
            LETSENCRYPT_EMAIL: contact@mariozechner.at
        networks:
            - reverse_proxy
networks:
    reverse_proxy:
        external:
            name: caddy-network
